/**
 * "Spot the trap" scenarios: situations where the tempting equation is wrong.
 * Hand-written. Each has 3–4 options, exactly one correct, and an explanation.
 */
export interface TrapScenario {
  id: string;
  topic: string; // chapter-ish label for filtering
  prompt: string; // inline $…$ allowed
  options: string[];
  correct: number; // index into options
  explanation: string;
  /** Equation ids that ARE appropriate (for linking). */
  equations: string[];
  /** The named error the tempting choice corresponds to. */
  errorId?: string;
}

export const TRAPS: TrapScenario[] = [
  // ---------- N ≠ mg ----------
  {
    id: "n-angled-push",
    topic: "Ch 5",
    prompt: "A crate is pushed across a rough floor by a force angled 30° BELOW the horizontal. To find the kinetic friction you need N. Which is right?",
    options: ["N = mg", "N = mg + F sin 30°", "N = mg − F sin 30°", "N = mg cos 30°"],
    correct: 1,
    explanation: "The push has a downward component F sin 30° that the floor must also support, so N = mg + F sin θ. N = mg is only true when nothing else has a vertical component.",
    equations: ["newton-2", "friction-kinetic"],
    errorId: "normal-equals-mg",
  },
  {
    id: "n-angled-pull",
    topic: "Ch 5",
    prompt: "A sled is pulled by a rope angled 25° ABOVE the horizontal on a rough surface. The normal force is",
    options: ["mg", "mg − T sin 25°", "mg + T sin 25°", "T cos 25°"],
    correct: 1,
    explanation: "The rope's upward component lifts part of the weight: ΣF_y = N + T sin θ − mg = 0 → N = mg − T sin θ. Less N means less friction.",
    equations: ["newton-2", "friction-kinetic"],
    errorId: "normal-equals-mg",
  },
  {
    id: "n-incline",
    topic: "Ch 5",
    prompt: "A block rests on a 35° incline. You want the maximum static friction μ_s N. Which N?",
    options: ["N = mg", "N = mg sin 35°", "N = mg cos 35°", "N = mg tan 35°"],
    correct: 2,
    explanation: "Perpendicular to the incline only N and the gravity component mg cos θ act, so N = mg cos θ. mg sin θ is the component ALONG the slope.",
    equations: ["newton-2", "friction-static"],
    errorId: "incline-sin-cos-swap",
  },
  {
    id: "n-elevator",
    topic: "Ch 5",
    prompt: "A person stands on a scale in an elevator accelerating UPWARD at 2 m/s². The scale reads",
    options: ["mg", "m(g + 2)", "m(g − 2)", "2m"],
    correct: 1,
    explanation: "ΣF_y = N − mg = ma with a = +2 → N = m(g + a). The scale reads the normal force, which exceeds mg whenever the acceleration is upward.",
    equations: ["newton-2"],
    errorId: "normal-equals-mg",
  },
  {
    id: "n-top-of-loop",
    topic: "Ch 6",
    prompt: "A roller-coaster car is at the TOP of a vertical loop (inside the track). The radial equation is",
    options: ["N − mg = mv²/r", "N + mg = mv²/r", "N = mg", "mg − N = mv²/r"],
    correct: 1,
    explanation: "At the top the center is below the car. Both the track's push N (downward, into the car) and gravity point toward the center, so they ADD: N + mg = mv²/r.",
    equations: ["sum-fc", "vertical-circle"],
    errorId: "top-bottom-loop-sign",
  },
  {
    id: "n-ferris-top",
    topic: "Ch 6",
    prompt: "A rider sits on a Ferris-wheel SEAT at the top of the wheel. The seat force N satisfies",
    options: ["N + mg = mv²/r", "mg − N = mv²/r", "N = mg", "N − mg = mv²/r"],
    correct: 1,
    explanation: "Unlike the inside of a loop, the seat is under the rider and pushes UP — away from the center. Gravity (toward the center) must exceed N by mv²/r: mg − N = mv²/r, so N < mg.",
    equations: ["sum-fc", "vertical-circle"],
    errorId: "top-bottom-loop-sign",
  },
  // ---------- kinematics requires constant a ----------
  {
    id: "kin-varying-force",
    topic: "Ch 7",
    prompt: "A particle is pushed by F(x) = 3x² N from x = 0 to x = 2 m. You want its final speed. Which approach is valid?",
    options: ["v² = v₀² + 2a Δx with a = F/m at x = 2 m", "W = ∫F dx, then W_net = ΔK", "v = v₀ + at with t = Δx/v_avg", "x = ½at² solved for a"],
    correct: 1,
    explanation: "The force (and so the acceleration) changes with position, so the constant-acceleration kinematics equations do not apply. Work–energy with W = ∫F dx handles a varying force.",
    equations: ["work-integral", "work-energy"],
    errorId: "area-as-F-times-d",
  },
  {
    id: "kin-spring",
    topic: "Ch 7",
    prompt: "A block is launched by a compressed spring. To find its launch speed you should use",
    options: ["v² = 2a d with a = kx/m", "the work–energy theorem with W_spring = ½kx²", "v = at with t from the spring's period", "F = ma then v = F t / m"],
    correct: 1,
    explanation: "The spring force decreases as it relaxes, so a is not constant and kinematics fails. The spring's work ½kx² equals the block's kinetic energy.",
    equations: ["work-spring", "work-energy"],
    errorId: "area-as-F-times-d",
  },
  // ---------- W = Fd cos θ vs varying force ----------
  {
    id: "work-varying",
    topic: "Ch 7",
    prompt: "F(x) = −2.0/x N acts on a particle moving from x = 2.0 m to 5.0 m. The work is",
    options: ["F(2.0) × 3.0 m", "F(5.0) × 3.0 m", "∫₂⁵ (−2.0/x) dx = −2.0 ln(5/2)", "the average of F(2) and F(5) times 3.0 m"],
    correct: 2,
    explanation: "W = Fd cos θ needs a constant force. For F(x) you integrate: ∫(−2/x)dx = −2 ln x. (Averaging endpoints only works for a LINEAR force.)",
    equations: ["work-integral"],
    errorId: "area-as-F-times-d",
  },
  {
    id: "work-graph",
    topic: "Ch 7",
    prompt: "An F–x graph shows a triangle rising from 0 to 10 N over 4 m. The work is",
    options: ["10 N × 4 m = 40 J", "½ × 10 N × 4 m = 20 J", "10 N × 4 m × cos 0° = 40 J", "cannot be found without the mass"],
    correct: 1,
    explanation: "Work is the area under the F–x curve. A triangle has area ½ × base × height = 20 J. Using the peak force times the distance overestimates by a factor of 2.",
    equations: ["work-integral"],
    errorId: "area-as-F-times-d",
  },
  // ---------- perpendicular → zero work ----------
  {
    id: "work-normal",
    topic: "Ch 7",
    prompt: "A box is dragged 5 m across a level floor. The work done by the normal force is",
    options: ["N × 5 m", "−N × 5 m", "zero, since N is perpendicular to the displacement", "mg × 5 m"],
    correct: 2,
    explanation: "W = Fd cos θ with θ = 90° between N and the horizontal displacement, so W = 0. Gravity also does zero work here.",
    equations: ["work-const"],
    errorId: "work-ignores-angle",
  },
  {
    id: "work-centripetal",
    topic: "Ch 7",
    prompt: "A ball on a string moves in a horizontal circle at constant speed. The work done by the string's tension over one revolution is",
    options: ["T × 2πr", "T × 2πr cos θ", "zero — tension is perpendicular to the velocity at every instant", "½mv²"],
    correct: 2,
    explanation: "The tension always points toward the center while the displacement is tangential; θ = 90° at every instant, so the tension does no work. Consistent with the constant speed (ΔK = 0).",
    equations: ["work-const", "work-energy"],
    errorId: "work-ignores-angle",
  },
  // ---------- static vs kinetic ----------
  {
    id: "static-not-max",
    topic: "Ch 5",
    prompt: "A 10 kg box sits at rest on a floor with μ_s = 0.5. Someone pushes horizontally with 20 N and it doesn't move. The static friction force is",
    options: ["μ_s mg = 49 N", "20 N", "μ_k mg", "zero"],
    correct: 1,
    explanation: "Static friction supplies only what is needed to prevent motion, up to its maximum μ_s N = 49 N. Since 20 N < 49 N, friction is exactly 20 N. Use μ_s N only on the verge of slipping.",
    equations: ["friction-static", "newton-2"],
    errorId: "static-max-not-needed",
  },
  {
    id: "kinetic-after-check",
    topic: "Ch 5",
    prompt: "A block at rest on a rough floor is pushed with a horizontal force F. Before computing an acceleration with f = μ_k N you must",
    options: ["check that F > μ_s N; if not, a = 0", "use μ_s instead of μ_k", "set F = μ_k N", "nothing — kinetic friction always applies once a force is applied"],
    correct: 0,
    explanation: "An object at rest stays at rest if the applied force is below the static limit. Only if F exceeds μ_s N does it start to move, and then kinetic friction μ_k N applies.",
    equations: ["friction-static", "friction-kinetic"],
    errorId: "didnt-check-static",
  },
  {
    id: "car-turn-static",
    topic: "Ch 6",
    prompt: "A car rounds a flat curve without skidding. The friction supplying the centripetal force is",
    options: ["kinetic, because the car is moving", "static, because the tires don't slide on the road", "rolling friction = μ_r N", "zero — the car is moving at constant speed"],
    correct: 1,
    explanation: "The contact patch of a rolling tire is momentarily at rest relative to the road, so the sideways friction that turns the car is STATIC friction, with f_s ≤ μ_s N.",
    equations: ["sum-fc", "friction-static", "vmax-flat-curve"],
    errorId: "static-vs-kinetic",
  },
  // ---------- radius vs diameter; rpm ----------
  {
    id: "ac-diameter",
    topic: "Ch 4",
    prompt: "A car makes a U-turn on a road of DIAMETER 200 m at 10 m/s. Its centripetal acceleration is",
    options: ["10²/200 = 0.5 m/s²", "10²/100 = 1.0 m/s²", "10/100 = 0.1 m/s²", "2π(100)/10"],
    correct: 1,
    explanation: "a_c = v²/r uses the RADIUS, which is half the diameter: r = 100 m. So a_c = 100/100 = 1.0 m/s².",
    equations: ["ac-v2-over-r"],
    errorId: "diameter-as-radius",
  },
  {
    id: "rpm-to-rad",
    topic: "Ch 4",
    prompt: "A fan spins at 300 rev/min with blade tips at r = 0.20 m. To get the tip's centripetal acceleration from a_c = rω², ω must be",
    options: ["300 rad/s", "300 × 2π rad/s", "300 × 2π / 60 rad/s", "300 / 60 rad/s"],
    correct: 2,
    explanation: "Convert revolutions to radians (×2π) AND minutes to seconds (÷60): ω = 300 × 2π / 60 = 31.4 rad/s. Formulas with ω require rad/s.",
    equations: ["rad-conv", "omega-def", "ac-v2-over-r"],
    errorId: "rpm-not-converted",
  },
  {
    id: "arc-length-degrees",
    topic: "Ch 4",
    prompt: "A point 0.5 m from an axis rotates through 90°. The distance it travels along its arc is",
    options: ["0.5 × 90 = 45 m", "0.5 × (π/2) = 0.785 m", "0.5 × 90 / 360 = 0.125 m", "2π × 0.5 = 3.14 m"],
    correct: 1,
    explanation: "s = rθ requires θ in radians: 90° = π/2 rad, so s = 0.5 × π/2 = 0.785 m.",
    equations: ["rad-conv", "arc-length"],
    errorId: "degrees-in-radian-formula",
  },
  // ---------- gravitation ----------
  {
    id: "g-altitude-r",
    topic: "Ch 13",
    prompt: "To find g at 400 km above Earth's surface with g = GM/r², the r you plug in is",
    options: ["400 km = 4.0 × 10⁵ m", "R_E = 6.37 × 10⁶ m", "R_E + 400 km = 6.77 × 10⁶ m", "R_E − 400 km"],
    correct: 2,
    explanation: "r is the distance from Earth's CENTER. The altitude must be added to the radius: r = R_E + h, converting km to m.",
    equations: ["g-altitude"],
    errorId: "altitude-not-plus-radius",
  },
  {
    id: "orbit-mass",
    topic: "Ch 13",
    prompt: "Two satellites of masses m and 3m orbit Earth at the same altitude. Their orbital speeds",
    options: ["differ by a factor of 3", "differ by a factor of √3", "are the same", "depend on how they were launched"],
    correct: 2,
    explanation: "Setting GMm/r² = mv²/r, the satellite's mass cancels: v = √(GM/r). Only the central mass and the orbit radius matter.",
    equations: ["v-orbit"],
    errorId: "orbit-mass-matters",
  },
  {
    id: "gravity-ratio",
    topic: "Ch 13",
    prompt: "The distance between two masses is tripled. The gravitational force between them becomes",
    options: ["1/3 as large", "1/9 as large", "3 times as large", "1/6 as large"],
    correct: 1,
    explanation: "F ∝ 1/r². Tripling r divides the force by 3² = 9. Scaling with 1/r is the classic slip.",
    equations: ["grav-force"],
    errorId: "inverse-not-inverse-square",
  },
  // ---------- banked / flat curve mass independence ----------
  {
    id: "banked-mass",
    topic: "Ch 6",
    prompt: "A frictionless curve is banked for cars at 20 m/s. A truck three times as heavy drives it at 20 m/s. It",
    options: ["needs a steeper bank", "needs a shallower bank", "is fine — tan θ = v²/(rg) has no mass in it", "slides outward because of its extra weight"],
    correct: 2,
    explanation: "Dividing N sin θ = mv²/r by N cos θ = mg cancels both N and m. The bank angle depends only on v and r.",
    equations: ["banked-angle"],
    errorId: "mass-not-weight",
  },
  {
    id: "flat-curve-mass",
    topic: "Ch 6",
    prompt: "On a flat curve with coefficient μ_s, the maximum speed for a heavy truck compared with a light car is",
    options: ["higher, because the truck has more friction", "lower, because the truck needs more centripetal force", "the same — v_max = √(μ_s g r)", "higher by a factor of the mass ratio"],
    correct: 2,
    explanation: "Both the available friction μ_s mg and the required force mv²/r scale with m, so m cancels: v_max = √(μ_s g r).",
    equations: ["vmax-flat-curve"],
    errorId: "mass-not-weight",
  },
  // ---------- tension ----------
  {
    id: "tension-accelerating",
    topic: "Ch 5",
    prompt: "A crate hangs from a crane cable and is accelerating upward at 1.5 m/s². The cable tension is",
    options: ["mg", "m(g + 1.5)", "m(g − 1.5)", "1.5m"],
    correct: 1,
    explanation: "T − mg = ma with a upward → T = m(g + a). T = mg holds only for zero acceleration (rest or constant velocity).",
    equations: ["newton-2"],
    errorId: "tension-equals-weight",
  },
  {
    id: "tension-pulley",
    topic: "Ch 5",
    prompt: "A block on a frictionless table is connected over a pulley to a hanging mass m₂ that is accelerating downward. The rope tension is",
    options: ["m₂g", "less than m₂g: T = m₂(g − a)", "greater than m₂g", "zero"],
    correct: 1,
    explanation: "For the hanging mass, m₂g − T = m₂a, so T = m₂(g − a) < m₂g. If T equalled m₂g the hanging mass could not accelerate.",
    equations: ["newton-2"],
    errorId: "tension-equals-weight",
  },
  // ---------- Hooke's law x ----------
  {
    id: "hooke-x",
    topic: "Ch 5",
    prompt: "A spring of natural length 20 cm and k = 100 N/m is stretched to a total length of 25 cm. The spring force is",
    options: ["100 × 0.25 = 25 N", "100 × 0.05 = 5 N", "100 × 0.20 = 20 N", "100 × 25 = 2500 N"],
    correct: 1,
    explanation: "In F = −kx, x is the displacement from the natural length: 25 − 20 = 5 cm = 0.05 m. And x must be in meters.",
    equations: ["hooke"],
    errorId: "cm-not-converted",
  },
  // ---------- angle in W = Fd cos θ ----------
  {
    id: "work-angle-reference",
    topic: "Ch 7",
    prompt: "A rope pulls a sled horizontally with the rope 30° above the horizontal. In W = Fd cos θ, θ is",
    options: ["30°, the angle between the rope and the (horizontal) displacement", "60°, the angle from the vertical", "90°", "0°, since the sled moves horizontally"],
    correct: 0,
    explanation: "θ is always the angle between the FORCE vector and the DISPLACEMENT vector. The displacement is horizontal and the rope is 30° from it.",
    equations: ["work-const"],
    errorId: "angle-complement",
  },
  {
    id: "work-opposing",
    topic: "Ch 7",
    prompt: "A 50 N force acts at 120° to a 2 m displacement. The work it does is",
    options: ["50 × 2 = 100 J", "50 × 2 × cos 60° = +50 J", "50 × 2 × cos 120° = −50 J", "50 × 2 × sin 120° = 87 J"],
    correct: 2,
    explanation: "cos 120° = −0.5: a force with a component opposite to the motion does negative work. Don't drop the sign by using the supplementary angle.",
    equations: ["work-const"],
    errorId: "work-sign-flip",
  },
  // ---------- misc ----------
  {
    id: "wnet-vs-single",
    topic: "Ch 7",
    prompt: "A block is pulled across a rough floor by a rope. To find its final speed with W = ΔK, the W you need is",
    options: ["the work done by the rope only", "the NET work: rope + friction (+ gravity and N, which are zero here)", "the work done by friction only", "the rope's work minus the kinetic energy"],
    correct: 1,
    explanation: "The work–energy theorem uses the work of ALL forces. Friction's negative work must be included or you will overestimate the speed.",
    equations: ["work-energy", "work-friction"],
    errorId: "forgot-friction",
  },
  {
    id: "power-seconds",
    topic: "Ch 7",
    prompt: "A motor does 9000 J of work in 3.0 minutes. Its average power is",
    options: ["9000/3 = 3000 W", "9000/180 = 50 W", "9000 × 180 W", "9000/60 = 150 W"],
    correct: 1,
    explanation: "A watt is a joule per SECOND. 3.0 min = 180 s, so P = 9000/180 = 50 W.",
    equations: ["power"],
    errorId: "minutes-not-converted",
  },
  {
    id: "conical-angle",
    topic: "Ch 6",
    prompt: "A conical pendulum's string makes 70° with the HORIZONTAL. In T cos θ = mg (vertical balance), θ should be",
    options: ["70°", "20°, the angle from the vertical", "either — cos and sin give the same result", "35°"],
    correct: 1,
    explanation: "The standard form uses the angle from the vertical so that T cos θ is the vertical component. From the horizontal, 70° means 20° from the vertical (equivalently T sin 70° = mg).",
    equations: ["conical-pendulum"],
    errorId: "angle-complement",
  },
  {
    id: "vmin-loop",
    topic: "Ch 6",
    prompt: "The minimum speed for a car to stay on the track at the top of a loop of radius r is found by setting",
    options: ["N = mg", "N = 0 in N + mg = mv²/r → v = √(gr)", "v = 0", "mg = 0"],
    correct: 1,
    explanation: "'Minimum speed' means the track is just about to stop pushing: N → 0. Then gravity alone supplies the centripetal force: mg = mv²/r.",
    equations: ["vertical-circle", "vmin-loop"],
    errorId: "normal-equals-mg",
  },
  {
    id: "third-law-cancel",
    topic: "Ch 5",
    prompt: "A horse pulls a cart. By Newton's third law the cart pulls back on the horse equally. The cart accelerates because",
    options: ["the horse's pull is slightly larger than the cart's", "the two forces act on DIFFERENT objects — only the forces on the cart determine its acceleration", "friction on the cart is zero", "third-law pairs don't apply to pulling"],
    correct: 1,
    explanation: "Third-law partners never cancel: they act on different bodies. The cart's acceleration comes from the net force ON THE CART (horse's pull minus friction).",
    equations: ["newton-2"],
    errorId: "third-law-same-object",
  },
];

export function trapById(id: string): TrapScenario | undefined {
  return TRAPS.find((t) => t.id === id);
}
